<?php

namespace Modules\Blog\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Blog\Models\Category;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = [
            'Artificial Intelligence',
            'Programming',
            'Design',
            'Business',
            'Marketing',
            'Education',
            'Health',
            'Travel',
            'Food',
            'Sports'
        ];

        foreach ($categories as $categoryName) {
            Category::create([
                'name' => $categoryName,
                // slug automatically generated by sluggable package
            ]);
        }
    }
}

